### ISSUE TITLE
card-mod styling

### ISSUE THREAD

**Issue by damyanor** [junkfix/numberbox-card#10]
Can you please allow styling a card with a standard ha-card component via card-mod repository?

**Comment by htmltiger** [comment]
```
type: entities
entities:
  - entity: input_number.living_ac_timer
    type: 'custom:numberbox-card'
    border: false
    style: |
      .cur-num{font-size:40px!important}

```
