### ISSUE TITLE
No slider?

### ISSUE THREAD

**Issue by Morphy99** [junkfix/numberbox-card#11]
I don't get a slider, am I missing something?
```
  - entity: input_number.lounge_trv_temp_morning
    type: 'custom:numberbox-card'
    icon: 'mdi:temperature'
    border: false
```

**Comment by Morphy99** [comment]
I thought it was because the input_number mode was set to default to box but no, it's slider. I've even tried specifying slider in the input_number but I still get a box on the custom card and a slider on the entity.

**Comment by Morphy99** [comment]
![image](https://user-images.githubusercontent.com/5853979/101160890-ae403500-3627-11eb-8d68-5ee075b8b3bd.png)
![image](https://user-images.githubusercontent.com/5853979/101160971-cadc6d00-3627-11eb-9ae6-5e9eceb98f6f.png)

**Comment by htmltiger** [comment]
try this way
```
type: entities
entities:
  - entity: input_number.living_ac_timer
    type: 'custom:numberbox-card'
    border: false
    style: |
      .cur-num{font-size:40px!important}
```
