### ISSUE TITLE
Quantity of increment

### ISSUE THREAD

**Issue by pillolola** [junkfix/numberbox-card#13]
Hi, how can I set the step of increase at 0,25

**Comment by htmltiger** [comment]
change step in the config
```
# Example configuration.yaml entry
input_number:
  slider1:
    name: Slider
    initial: 30
    min: -20
    max: 35
    step: 0.25
```
