### ISSUE TITLE
Hold +/- for fast adjustment?

### ISSUE THREAD

**Issue by jamesmyatt** [junkfix/numberbox-card#22]
Can you add a hold action that makes a fast adjustment? It's a bit boring to have to press the button for every step when you want to make a big change.

**Comment by htmltiger** [comment]
It would be complicated as we need to hook touch events to detect hold.

The workaround I use is mode: box
for any big change click on the title for the more info and change it from there
```
input_number:
  box1:
    name: Numeric Input Box
    initial: 0
    min: 0
    max: 3500
    step: 1
    mode: box
```
