### ISSUE TITLE
Unit of measurement

### ISSUE THREAD

**Issue by julienlarivee** [junkfix/numberbox-card#5]
Hi,

Would it be possible to add the unit of measurement inside the selector?
Like in the simple thermostat card in compact mode just next to the + sign.

![image](https://user-images.githubusercontent.com/55027006/99208763-744de280-278f-11eb-9605-880f2d51786c.png)

Thank you

**Comment by tdonhauser** [comment]
That would be great! I would need the same feature...

**Comment by Morphy99** [comment]
+1

**Comment by htmltiger** [comment]
added

**Comment by tdonhauser** [comment]
> added

Thanks a lot!

**Comment by Morphy99** [comment]
I'm using the material red theme and the unit appears a different colour to the number. Is this by design or can this be tweaked?
![image](https://user-images.githubusercontent.com/5853979/101371614-de473c80-38a2-11eb-888b-40f810c70b19.png)

**Comment by htmltiger** [comment]
> I'm using the material red theme and the unit appears a different colour to the number. Is this by design or can this be tweaked?
> ![image](https://user-images.githubusercontent.com/5853979/101371614-de473c80-38a2-11eb-888b-40f810c70b19.png)
adding the following style should fix it if you use card mod for styles

```
type: entities
entities:
  - entity: input_number.my_slider
    type: 'custom:numberbox-card'
    icon_plus: 'mdi:chevron-up'
    icon_minus: 'mdi:chevron-down'
    style: |
      .cur-unit{ font-size:100% !important; opacity:1 !important }

```

the default is 
```
.cur-unit{font-size:80%;opacity:0.5}
```
