### ISSUE TITLE
Decrease height of number box row 

### ISSUE THREAD

**Issue by eyalcha** [junkfix/numberbox-card#8]
Seems that the number box have higher height than the normal slider card.

**Comment by htmltiger** [comment]
buttons have bigger touch area and its best to keep it away from getting too close to other.

**Comment by nagyrobi** [comment]
I'd like to use this card with my [smart heating control](https://github.com/nagyrobi/home-assistant-configuration-examples/tree/main/heating) but because the height is so much bigger it breaks the entire layout, see:
![kép](https://user-images.githubusercontent.com/1550668/104916617-9d0e7600-5992-11eb-83c2-6ed5bcb2dd8d.png)

The original was:
![kép](https://user-images.githubusercontent.com/1550668/104916797-d47d2280-5992-11eb-8c65-ecfa5363ebd9.png)

Please add a configurable option to stay within HA's standard entity height.

**Comment by htmltiger** [comment]
try something like this and see if it helps:

```
type: entities
entities:
  - entity: input_number.living_ac_timer
    type: 'custom:numberbox-card'
    style: |
      .grid-left{font-variant: small-caps}
style: |
  #states{padding:0px 10px !important}
  #states>*{margin:0 !important}
```

![image](https://user-images.githubusercontent.com/1429451/105606540-e6dfcd80-5d91-11eb-9913-a60612dfd2af.png)

**Comment by nagyrobi** [comment]
Tried, still much bigger than the original controls:
```
type: horizontal-stack
cards:
  - type: entities
    entities:
      - entity: input_number.heating_temp_morning
        type: 'custom:numberbox-card'
        style: |
          .grid-left{font-variant: small-caps}
      - entity: input_number.heating_temp_day
        type: 'custom:numberbox-card'
        style: |
          .grid-left{font-variant: small-caps}
      - entity: input_number.heating_temp_evening
        type: 'custom:numberbox-card'
        style: |
          .grid-left{font-variant: small-caps}
      - entity: input_number.heating_temp_night
        type: 'custom:numberbox-card'
        style: |
          .grid-left{font-variant: small-caps}
    title: Kívánt hőmérsékletek
    show_header_toggle: false
    style: |
      #states{padding:0px 10px !important}
  - type: entities
    entities:
      - entity: input_number.heating_temp_morning
      - entity: input_number.heating_temp_day
      - entity: input_number.heating_temp_evening
      - entity: input_number.heating_temp_night
    title: Kívánt hőmérsékletek
    show_header_toggle: false
```
![kép](https://user-images.githubusercontent.com/1550668/105607433-faddfc00-5d9e-11eb-8954-b1ebe0ce4d47.png)

**Comment by htmltiger** [comment]
I have edited the reply with additional ` #states>*{margin:0 !important}`

![image](https://user-images.githubusercontent.com/1429451/105607467-da11a880-5d96-11eb-9062-ea35fce01322.png)

**Comment by nagyrobi** [comment]
Thanks. It's still a little too much, see:
![kép](https://user-images.githubusercontent.com/1550668/105607634-23b2c100-5da0-11eb-8b07-eb10bd35f52b.png)

**Comment by nagyrobi** [comment]
It would be still very good with a smaller touch area so they all fit in parrallel. Really. Please make the touch area configurable.

**Comment by htmltiger** [comment]
We need to find a way to change  `ha-icon-button` size or height, its taking it from the theme

for now you can try increasing the padding of sliders to match

```

type: horizontal-stack
cards:
  - type: entities
    entities:
      - entity: input_number.heating_temp_morning
        type: 'custom:numberbox-card'
        style: |
          .grid-left{font-variant: small-caps}
      - entity: input_number.heating_temp_day
        type: 'custom:numberbox-card'
        style: |
          .grid-left{font-variant: small-caps}
      - entity: input_number.heating_temp_evening
        type: 'custom:numberbox-card'
        style: |
          .grid-left{font-variant: small-caps}
      - entity: input_number.heating_temp_night
        type: 'custom:numberbox-card'
        style: |
          .grid-left{font-variant: small-caps}
    title: Kívánt hőmérsékletek
    show_header_toggle: false
    style: |
      #states{padding:0px 10px !important}
      #states>*{margin:0 !important}
  - type: entities
    entities:
      - entity: input_number.heating_temp_morning
      - entity: input_number.heating_temp_day
      - entity: input_number.heating_temp_evening
      - entity: input_number.heating_temp_night
    title: Kívánt hőmérsékletek
    show_header_toggle: false
    style: |
      #states>*{padding-top:10px !important;padding-bottom:10px !important}

```

in the last 2 lines, change 10px to your needs
